apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-dashboard
  namespace: student-11
  labels:
    app: health-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-dashboard
  template:
    metadata:
      labels:
        app: health-dashboard
    spec:
      containers:
        - name: api
          image: python:3.12-slim
          imagePullPolicy: IfNotPresent
          workingDir: /app
          command: ["sh", "-c"]
          args:
            - |
              set -e
              apt-get update
              apt-get install -y --no-install-recommends git ca-certificates
              rm -rf /app/*
              git clone --depth 1 --branch main https://github.com/Sak3th2004/SRE_Devops_Mini_Project.git /tmp/src
              cp -a /tmp/src/. /app/
              pip install --no-cache-dir -r requirements.txt
              exec gunicorn -b 0.0.0.0:5000 app:app
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: health-dashboard-config
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 90
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 120
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
