apiVersion: v1
kind: Service
metadata:
  name: health-dashboard
  namespace: student-11
  labels:
    app: health-dashboard
spec:
  type: NodePort
  selector:
    app: health-dashboard
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30080
