apiVersion: 1
datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
  - name: Trainer Prometheus
    uid: trainer
    type: prometheus
    access: proxy
    url: http://43.205.104.60:9090
    editable: true
